strongloop/loopback-component-explorer

.gitignore, lib/class-helper.js, lib/model-helper.js, lib/route-helper.js, lib/swagger.js, package.json, public/css/loopbackStyles.css, public/index.html, test/class-helper.test.js, test/model-helper.test.js, test/route-helper.test.js
=> Pick up enhancements from shelbys master

CONTRIBUTING.md, LICENSE, README.md, index.js, package.json, test/explorer.test.js
=> Rename package and module

public/lib/loadSwaggerUI.js
=> disable Swagger validation badge

index.js, test/explorer.test.js
See https://github.com/strongloop/loopback-component-explorer/issues/153
=> Add `swaggerUI` option to enable/disable UI serving

index.js
Partially revert 298765547 (#156).
@Amir-61 @superkhau please review
=> Fix broken indentation

package.json
Connect to strongloop-internal/scrum-loopback#1055
cc @gunjpan @richardpringle
=> Use loopback@3.0.0-alpha for running the tests.

test/explorer.test.js
Can merge after https://github.com/strongloop/loopback/pull/2781 has landed.
=> Use new api for disabling a remote method.

intl/ja/messages.json
https://github.com/strongloop-internal/scrum-loopback/issues/1097
=> Update translation files - round#2

package.json
In preparation for https://github.com/strongloop/loopback-component-explorer/pull/182
=> Start 3.0 development

index.js, package.json, public/index.html
Reverts #107.
Fixes: 
* https://github.com/strongloop/strong-swagger-js/pull/11
* https://github.com/strongloop/strong-swagger-ui/pull/13
* Many [open Issues](https://github.com/strongloop/loopback-component-explorer/issues)
=> [SEMVER-MAJOR] Update to mainline swagger-ui 

public/index.html
should fix https://github.com/strongloop/loopback-component-explorer/issues/185
i was facing same issue, this should fix it, not familiar with this module, just copied [this](https://github.com/swagger-api/swagger-ui/blob/552865aa0d990475dfccfde6baa4f28bb7398975/dist/index.html#L25)
@bajtos PTAL
cc @STRML
=> Fix jsoneditor not defined error

public/css/loopbackStyles.css
a few line termination fixes in CSS
=> CSS line terminations

public/css/loopbackStyles.css
=> Backport: CSS line terminations

README.md
=> Added another example for explorer Advanced Usage

README.md, package.json
=> Prepare for 4.x GA

package.json
=> Update package.json for LTS release

README.md
connect to strongloop-internal/scrum-loopback#1437
replace slc usage with lb
=> replace slc with lb

index.js, test/explorer.test.js
Rework on https://github.com/strongloop/loopback-component-explorer/pull/208
=> Refresh swagger on remoteMethodAdded

intl/cs/messages.json, intl/pl/messages.json, intl/ru/messages.json
Czech, Polish, Russian translation check-in by YI TANG (tangyinb@cn.ibm.com) using WebFM tool.
=> [WebFM] cs/pl/ru translation Check-in by YI TANG (tangyinb@cn.ibm.com)

package.json
This is required by https://github.com/strongloop/loopback-component-explorer/pull/255 where we are starting to use ES6 features - template literals.
=> Update eslint & config to latest

README.md
- connect to <link_to_referenced_issue>
=> Updated README with small code fix.

public/lib/loadSwaggerUI.js, test/fixtures/dummy-swagger-ui/swagger-ui.js
- connect to https://github.com/strongloop-internal/scrum-apex/issues/406
=> chore: update copyrights years

.travis.yml, package.json
- connect to <link_to_referenced_issue>
=> Drop Node.js 6 and add Node.js 12 to Travis CI

public/css/loopbackStyles.css
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-component-explorer) 👈
=> Use "cursor: pointer" for the "Add token" button
