- public/index.html
Allows people to open the explorer in IE without constantly changing the document mode.
> Add X-UA-Compatible tag

- index.js
- test/explorer.test.js
See strongloop/loopback-explorer/issues/81
> Allow `uiDirs` to be defined as a String

- lib/swagger.js
- test/explorer.test.js
SwaggerUI builds resource URL by concatenating basePath + resourcePath.
Since the resource paths are always startign with a slash, if the
basePath ends with a slash too, an incorrect URL is produced.
This was typically happenning when `restApiRoot` was '/'.
This commit modifies the code producing the base path to remove
the trailing slash.
Fix #48.
/to @raymondfeng or @STRML please review
/cc @marcopeise
> Prevent double slash in the resource URLs

- lib/class-helper.js
- test/class-helper.test.js
Currently loopback-explorer sets the value of `resourcePath` to `opts.resourcePath` for each and every Model in the application that exposes a REST API.
In my understanding of the [API Declararion part](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#52-api-declaration) of the Swagger 1.2 spec, this is not correct. 
The correct way would be for each Model to have it's own resourcePath since each Model has it's own API Declaration.
Moreover, the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) tool uses the value of `resourcePath` to organize the resources into classes (at least in Java). 
What this means is that with the current `loopback-explorer` implementation, the generated client code for the whole API exposed by the server, will be contained …
> Made API doc of class use the http.path of the class if available

- public/index.html
We are shipping a custom style that uses "Ubuntu" instead of "Droid
Sans", thus there is no need to download the "Droid Sans" font
from Google's CDN.
This change should improve explorer's loading time in the situations
where the external URL takes too long to load or cannot be loaded at
all, for example when running behind a restricting proxy.
Fix #74.
/to @raymondfeng or @STRML please review
I run the following two greps to verify that our custom style is overriding all references to  "Droid Sans":
```
grep font-family -r public node_modules/swagger-ui/dist
grep Droid -r public node_modules/swagger-ui/dist
```
> Remove unused external font "Droid Sans".

- test/explorer.test.js
Some test cases in explorer.test.js, failed on Windows, owing to different line endings. Fixed them, so that they work on Windows as well.
@bajtos , can you please review?
> Fix explorer tests for different line endings on Windows

- public/index.html
Referring to  - https://github.com/strongloop/loopback-explorer/issues/85
reset.css and screen.css were duplicated in index.html, for "screen" and "print" media.
Removed the duplicate entries and provided "screen" and "print" as multiple media options for "media" attribute.
@bajtos, can you please review?
> Fix duplicate stylesheet issue

- public/lib/loadSwaggerUI.js
By default in loopback, if a token is submitted via header or querystring, but it is invalid, the method will not be run.
Unfortunately this is also even true of the `/login` method. This causes the following broken workflow:
1. The user's token expires. This can happen over time (idle browser), or if the browser is re-opened and the token was saved in localStorage, or the user intentionally loggedout.
2. The user wants to get a valid token. The user submits to `/user/login` with credentials to get a new token.
3. The default `token` middleware refuses the request due to an invalid access token.
The user needs to be able to delete the current token so he/she can resubmit.
This PR allows submitting the text box with an empty value to remove the current token.
> Allow submitting token input with empty value to remove token.

- lib/swagger.js
- test/swagger.test.js
A follow-up for #95. When the new option is enabled, base path is always set to a protocol-relative URL.
/to @STRML @raymondfeng could one of you review please?
/cc @billinghamj
> Add options.omitProtocolInBaseUrl

- index.js
- package.json
- public/index.html
1) Extract all CSS customizations from `screen.css` to `loopbackStyles.css`, so that we use swagger-ui styles and get all improvements made in the last two years. It took me a while to find the right base commit and get a reasonable diff, I ended up using https://github.com/swagger-api/swagger-ui/blob/e980cca6b4218290ce4e5ab22f129c735dbecb27/dist/css/screen.css
2) Replace the dependency on swagger-ui with strong-swagger-ui, which is StrongLoop's fork of swagger-ui v2.0.x with additional enhancements
3) Drop public/images/throbger.gif, use the one provided by strong-swagger-ui. This will make it easier to inline this particular file inside CSS via data-uri.
Connect to strongloop-internal/scrum-loopback#112
/to @raymondfeng @ritch please review
/cc @STRML FYI
BTW my intention is to release …
> Switch to strong swagger ui

- README.md
- index.js
- package.json
- test/explorer.test.js
- test/swagger.test.js
Rework the exported function to conform to the component convention:
var loopback = require('loopback');
var explorer = require('loopback-explorer');
var app = loopback();
explorer(app, options);
- drop dependency on express
- drop support for loopback 1.x
- add a new option "mountPath" to specify where to mount the explorer UI
and swagger metadata
Close #21 
/to @raymondfeng @ritch please review
/cc @STRML
> [SEMVER-MAJOR] Rework the module to a loopback component

- index.js
- package.json
- public/index.html
- public/lib/loadSwaggerUI.js
This patch upgrades loopback-explorer to use strong-swagger-ui@21.0, which is based on swagger-ui@2.1 and supports Swagger Spec 2.0.
**Notes**
- strong-swagger-ui@21.0 does not implement all customizations from v20.0 yet, I'll be working on that in follow-up pull requests.
- For endpoints `GET /models`, the response model is not correctly rendered ATM. I suspect this is caused by #111 and/or #113, I'll be investigating the problem after this PR is landed.
Connect to strongloop-internal/scrum-loopback#412
Connect to strongloop/loopback-explorer#54
/to @raymondfeng @STRML please review
> Upgrade to strong-swagger-ui@21.0 (swagger-ui@2.1)

- index.js
- test/explorer.test.js
This patch registers loopback-explorer to the app object with its
options, making its mountPath property available at
app.get('loopback-explorer').
> Register loopback-explorer to app

- public/lib/loadSwaggerUI.js
This was working in 1.x but broke in 2.x due to an API change in swagger-ui.
Sorts APIs alphabetically.
Sorts operations alphabetically then by method.
> Sort APIs and operations.

- index.js
- test/explorer.test.js
This PR is for strongloop/loopback#686 to make the explorer registering a remoteMethodDisabled event that is fired from PR strongloop/loopback#2266. The explorer will update a swagger object when getting this event to hide the disabled remote method.
> Allow disabling remote method after initialize explorer

- package.json
The "hide disabled remote methods after explorer is initialized" feature requires loopback 2.28.0. So, upgrade devDependency to make it more explicit about minimum requirement.
> Upgrade loopback devDependency

- test/explorer.test.js
Currently, `npm run test` fails the 'overrides swagger-ui files' test because the content inside `dummy-swagger-ui/swagger-ui.js` was prepended by copyright notice. This fix ignores the copyright notice and checks only that the file contains `/* custom swagger-ui file */`.
> [Fix] `overrides-swagger-ui files` test ignores copyright in dummy file. 

- test/explorer.test.js
Connect to CI failure: https://github.com/strongloop-internal/scrum-loopback/issues/915#issuecomment-226798303
Redirect to /explorer/ expects a http 301 instead of 303.
> Redirect get http 301 instead of 303

- .gitignore
- example/hidden.js
- example/simple.js
- index.js
- intl/en/messages.json
- package.json
Connect to strongloop/loopback/issues/2422
> Add globalization

- index.js
- package.json
- test/explorer.test.js
Push the responsibility of enabling/configuring CORS back to the application developer.
This is a follow-up for https://github.com/strongloop/strong-remoting/pull/352 and https://github.com/strongloop/strong-remoting/pull/357 which removed (3.x)/deprecated (2.x) the built-in CORS middleware in strong-remoting.
@richardpringle please review
> Deprecate built-in CORS middleware

- package.json
- test/explorer.test.js
Connect to strongloop-internal/scrum-loopback#1063
> Update deps to loopback 3.0.0 RC

- package.json
Compared to #200 I'd like to apply the version to 3.0.1, for the reason of `default: null` being filtered out of the swagger.json since 22nd of december 2016. Please do as you like (:
- None
> bump loopback-swagger version to 3.0.1

- public/css/loopbackStyles.css
Sometimes fields are hovering over the header
> Set z-index to 1 on header to fix styling bug

- public/index.html
- test/explorer.test.js
Sumitha asked if we could change the title of the LoopBack explorer to read LoopBack API Explorer instead of StrongLoop API Explorer.
- None
> Change Explorer header to use LoopBack vs StrongLoop

- package.json
Increment loopback-swagger version to ^4.0.0 which supports updateOnly feature. Without this loopback-cli --> create new app --> will not pick up the new 'updateOnly' feature https://github.com/strongloop/loopback/issues/2924
> Increment loopback-swagger version to 4.x

- package.json
Current master points to  "loopback-swagger": "^4.0.0" which has "updateOnly" support. 
@raymondfeng PTAL
> Increment package version to 5.0.0

- CODEOWNERS
See https://github.com/strongloop/loopback-component-explorer/pull/219#issuecomment-326441810
> Could you please take me off the automatic review bot?
@STRML sorry for the inconvenience. This pull request should disable PR review notifications for you in this repository, see [this github docs](https://help.github.com/articles/about-codeowners/) for more details about CODEOWNERS.
I think you are listed as a code owner in few more repositories. I there are any other repositories where you are receiving PR review requests that you are not interested in, then please open a pull request to apply a similar changes to CODEOWERS as done in this patch, or let me know e.g. on Gitter and I can do that myself.
> CODEOWNERS: turn off PR notifications for STRML

- package.json
@raymondfeng PTAL.. 
Note: CI will not pass until loopback-swagger PR https://github.com/strongloop/loopback-swagger/pull/99 is merged and loopback-swagger is published as 5.0.0 release.
> Use loopback-swagger major version  

- package.json
This change fixes the following security vulnerability:
- [npm:lodash:20180130](https://snyk.io/vuln/npm:lodash:20180130)
> Upgrade lodash from 3.x to 4.x

- index.js
> There are links to docs.strongloop.com in various places in the code that we should replace with links to the new doc site loopback.io/doc.
Originated from: https://github.com/strongloop-internal/scrum-loopback/issues/1108
One change in this PR and the rest are coming from the linter:
- update link in `index.js` point to https://loopback.io/doc/en/lb3/Security-considerations.html
> docs: update docs link away from docs.strongloop.com

- index.js
- package.json
- test/explorer.test.js
When I use loopback 3, and initialize the explorer component,
I get an annoying warning when remotes.options.cors is undefined.
loopback-explorer deprecated The built-in CORS middleware provided by loopback-component-explorer was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. server/server.js:29:3
loopback-explorer deprecated The built-in CORS middleware provided by loopback-component-explorer was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. node_modules/loopback-boot/lib/executor.js:445:5
I think it could be solved with this little validation.
> [SEMVER-MAJOR] Remove deprecated CORS support

- package.json
I was using `loopback-component-explorer@4.3.0` and having a NSP vulnerability warning (Ref: https://nodesecurity.io/advisories/577)
These are the compatibility-warnings for upgrading `lodash` from v3 to v4 (https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings)
> Fix lodash vulnerability: Prototype Pollution

- README.md
Update the information about the support status of loopback-component-explorer versions (don't confuse it with Node.js version1).
- 6.x is active
- 5.x is LTS
- 4.x is in maintenance
- 2.x is no longer supported
@dhmlau @strongloop/sq-lb-apex PTAL
> Update LTS information in README

- README.md
- index.js
- public/lib/loadSwaggerUI.js
- test/explorer.test.js
This PR makes 2 changes for increased flexibility, useful (in some cases necessary) when using the explorer behind a third party api gateway. 
1. Adding an `auth` option for setting the access token as a request header or renaming the query parameter.
2. Allow the explorer to run from `<mountPath>/index.html`. With the existing defaults this will cause an error trying to load `<mountPath>/index.html/swagger.json`
> Add config option for setting api token

- .eslintignore
- example/hidden.js
- example/simple.js
- index.js
- lib/url-join.js
- package.json
- test/explorer.test.js
This is required by #255 where we are starting to use ES6 features - template literals. See also #256 where I accidentally upgraded only to the latest compatible version.
> Update eslint & config to latest major versions

- test/explorer.test.js
To prevent accidental upgrades to a new (and very incompatible) version of swagger-ui, I am proposing to add an explicit version check that will abort the test suite when upgrade is detected.
```
$ npm t
> loopback-component-explorer@6.3.1 test /Users/bajtos/src/loopback/component-explorer
> mocha
Upgrading from swagger-ui@2 to a newer major version is difficult, see
https://github.com/strongloop/loopback-component-explorer/issues/254
If you are confident about this change and have manually verified API Explorer
functionality in the browser, including access-token based authentication,
then you can delete this check.
npm ERR! Test failed.  See above for more details.
```
See #250, #253 and and #254.
> Prevent accidental upgrades to swagger-ui v3+

- README.md
- example/hidden.js
- example/simple.js
- index.js
- lib/url-join.js
- package.json
- public/lib/loadSwaggerUI.js
- test/explorer.test.js
- test/fixtures/dummy-swagger-ui/swagger-ui.js
Related to https://github.com/strongloop/loopback/issues/4180
- Update `README` for the LTS status
- Update `package.json` `author` attribute so that the `slt copyright` command can generate the right copyright header
- Run `slt copyright` command to update the copyright years
> update README for LTS status

- README.md
Update README to explain we're not affected by the swagger-ui security vulnerability. 
https://github.com/strongloop/loopback-component-explorer/issues/263#issuecomment-529385166
https://github.com/strongloop-internal/scrum-apex/issues/432
- connect to <link_to_referenced_issue>
> Update README on swagger-ui

- README.md
Update README - explain why this vulnerability is not affecting LoopBack users.
The patch is best reviewed commit by commit. The first commit improves README formatting, the second commits adds the new text.
See also #263
👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-component-explorer) 👈
- New tests added or existing tests modified to cover all changes
> Describe GitHub advisory CVE-2019-17495 
